gogs/git-module

tree_entry.go
https://github.com/gogits/gogs/issues/2254
=> try to fix  Duplicate of files in directory (gogs#2254 )

commit.go, repo_commit.go, tree_entry.go
* 1st commit - fixes regression causing no submodule info being loaded at all introduced in ebd9fb2
* 2nd commit - do not fail in GetCommitsInfo with no .gitmodules, causing 500 internal error in Gogs
See commit descriptions for more details.
=> Fix submodule info loading

repo_tag.go
=> Reverse the order of tags below git 2.0

repo_tag.go
Since #8, when a repo has no tags, then a non empty tag list is returned (`[""]`). Reference: gogits/gogs#2880
I made this mistake by replacing the previous implementation (`tags[:len(tags)-1]`) with `strings.TrimSpace(stdout)`. This worked fine, then there were tags, but created an invalid list otherwise.
This PR fixes this.
Sorry for my mistake!
=> Fixed returning non empty tag list when there are no tags.

commit.go, repo.go, repo_commit.go
This is needed for the PR #3092 on https://github.com/gogits/gogs/issues/1071 for editing files. What was needed was a way to set the branch when making a pull, checking out a branch, and moving a file with git mv. This is now all implemented.
=> Added functions to handle checking out branches and moving files

repo_commit.go
Support shorter commit IDs than 40 characters.
The default length of abbrev is 7 chars, and the absolute minimum is 4 chars. 
This is useful when the user only have the abbrev of a commit id.
=> Add support for abbreviated commit IDs

submodule.go
According to git submodule documentation base path for relative submodule URL
is parent repository's root - not submodule "mount point".
So it's necessary to know "path" of parent repository to create correct submodule
URL.
Unfortunately, RefUrl function semantics are changed (kind of API change), so it can break something else that uses it. 
At least it is required to change /templates/repo/view_list.tmpl in gogs project.
For more details see issue gogits/gogs#1926
Thus, maybe it's even better to make new function (temporary or permanently) similar to RefUrl (I don't know how bad it is to break compatibility in this particular case).
=> Fixed incorrect relative submodule URLs

commit.go
Probably speeds up counting commits for git versions < 1.8.0,
although I dubt it would make a visible difference
=> Avoid creating an array for the sole purpose of counting elements

tree_entry.go
This pull request remove usage of _sleep_ function who slow down git repos browsing (Issue #18).
=> Fix #18: Sleep induced slowness in gogits

tree.go
Fixes #22 Missing mode in parseTreeData (tree.go)
=> Add mode for regular, group-writeable file

tree_entry.go
This pull request add ability to set the maximum number of goroutine allowed on the function `GetCommitsInfo` (issue #25). If the given number is equal of lower than 0, the function `runtime.NumCPU()` will be used.
=> Feature #25: Custom max number of goroutine

repo.go
According to https://git-scm.com/docs/git-count-objects only 'size', 'size-pack' and, 'size-garbage' are reported in KiB. 'in-pack' is just a number.
=> Fix count-objects InPack incorrectly multiplied by 1024

repo.go
Git count-objects was introduced in 1.8.3.
=> Check unsupported version in GetRepoSize

repo_commit.go
https://github.com/gogits/gogs/issues/4855
The Repository#getCommit method's call to `git cat-file` succeeds if the `<object>` argument is a object reference, regardless of object type. If the `id` parameter of a blob is passed to the method, the command will run without an error and `parseCommitData` will panic when attempting to parse the blob data. 
Restrict Repository#getCommit method call to `git cat-file` to only succeed if the `<object>` argument is a commit object reference by replacing the `-p` flag with a `<type>` argument with value `commit`. 
This makes it such that if the object reference is valid but not a commit, e.g. a blob, the command will return a non-zero exit status and the method will return an error instead of panicking when attempting to parse the data.
`-p`flag …
=> Fix issue with object IDs resulting in an exception

command.go, commit.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

command.go, repo.go, repo_commit.go, repo_commit_test.go, repo_hook.go, repo_hook_test.go, repo_pull.go, repo_reference.go, repo_reference_test.go, repo_tag.go
Adjustment with migration on main repository.
=> v1.0.0-beta.3

tree_blob.go
This PR adds an `or` conditional to return blob content if a file is an
executable (entry mode 0100755). Prior to this `Blob` func only returned
file contents if a file was of type blob (entry mode 010644). This in a
resulted error to be returned for certain files that were for instance
bash scripts which had the executable mode bit set.
=> tree_blob: return blob contents for blob and exec (#56)

tree_blob.go, tree_blob_test.go
=> tree_blob: add tests

tree_entry.go
to fix https://github.com/gogs/gogs/issues/6186
to fix https://github.com/gogs/gogs/issues/6235
to fix https://github.com/gogs/gogs/issues/6240
The problem is on git-module
https://github.com/gogs/git-module/blob/cf0a6d71b880c42c4dd507b59be762c5a05c649a/tree_entry.go#L261-L270
An entry id is not unique so it should not be used as map key. When on a tree there is a file or folder with same contents its SHA1 hash is equal. This can be tested in any repo with two files with same content executing `git ls-tree HEAD`
```cmd
$ mkdir testrepo; cd testrepo
$ git init
$ echo "this is a test" > test1
$ git add .
$ git commit -m "adding test1 file"
$ echo "this is a test" > test2
$ git add .
$ git commit -m "adding test2 file"
$ git ls-tree HEAD
100644 blob 90bfcb510602aa11ae53a42dcec18ea39fbd8cec …
```
=> tree_entry: fix CommitsInfo messed up with entries have the same SHA1

commit_submodule.go
for example, the .gitmodules in https://git.zx2c4.com/cgit is like this:
```.gitmodules
[submodule "git"]
url = https://git.kernel.org/pub/scm/git/git.git
path = git
```
=> Fix bad parsing for some .gitmodules that path and url not ordered

blame.go, blame_test.go
Needed for https://github.com/gogs/gogs/issues/2606
=> Add "git blame" parser

diff.go, diff_test.go, repo_diff.go, repo_diff_test.go
This adds some missing information needed to constructe a full-index
diff from DiffFile struct type. It adds old/new file mode, index, and
name.
=> diff: capture both old and new of index and mode

command.go, go.mod, repo.go, repo_blame.go, repo_commit.go, repo_diff.go, repo_pull.go, repo_reference.go, repo_remote.go, repo_tag.go, repo_tree.go
* Fix "signed shift count 4 (untyped int constant) requires go1.13 or later" compiler warning by updating go.mod go version to 1.13
* Add the ability to pass extra envs and args to commands
* Pass stdin to RunInDirWithPipelineTimeout
Passing stdin to RunInDirWithPipelineTimeout is useful when using Git server over ssh for example https://github.com/charmbracelet/wish/blob/0e458e40c040539ab25d5ba82859179091746648/git/git.go#L193-L202
=> Add command options and pass stdin to command

repo.go, repo_tree.go
* cache repo trees
Cache tree objects
=> feat: cache tree objects

repo_blob.go, repo_blob_test.go
Add a method that returns any Blob object by its corresponding hash.
Link to the issue: gogs/gogs#5979
=> feat(repo_blob): add CatFileBlob

repo_reference.go
Link to the issue: https://github.com/gogs/gogs/pull/7291
=> chore: expose `SymbolicRef` as standalone function

repo.go, repo_test.go
Fixes #65
This fixes a typo in `AddOptions`.
Given this changes the public API, an alternative would be to deprecate `Pathsepcs`, add `Pathspecs`, and add a small shim. I'm happy to do that if y'all would rather :)
Link to the issue: #65
=> fix: typo in struct AddOptions

git_test.go, repo_diff.go, repo_grep.go, repo_grep_test.go
Use `git grep` to search files in a repository.
=> feat(grep): search a repository

tree_entry.go
Git itself allows adding another Git repository inside the current repository without properly defining as a submodule, so we need to be tolerant about that.
Link to the issue: https://github.com/gogs/gogs/issues/6436
=> fix: be tolerant to implicit submodules

command.go, command_test.go, repo.go, repo_blame.go, repo_blob.go, repo_commit.go, repo_diff.go, repo_grep.go, repo_pull.go, repo_reference.go, repo_remote.go, repo_tag.go, repo_tree.go
Pass a context down to *exec.Command and make timing out optional when o.Timeout < 0.
Using `context.Background()` _all the time_ is not practical as sometimes we need to stop the execution when _a_ parent context stops.
A clear and concise description of what the pull request is about, i.e. what problem should be fixed?
Link to the issue:
=> feat: run command with context

repo_reference.go, server.go, server_test.go
Add server-side git commands for handling git services. This includes git-upload-pack, git-upload-archive, and git-receive-pack services. Also add git-update-server-info helper.
A clear and concise description of what the pull request is about, i.e. what problem should be fixed?
Link to the issue:
=> feat: add server-side git commands

.github/workflows/go.yml, CODEOWNERS, repo_tag.go
Fixes https://github.com/gogs/gogs/security/advisories/GHSA-m27m-h5gj-wwmg
=> repo_tag: ignore unintended Git options when creating tags
